FORMAT: 1A

# event-guide
Event Guide manages the data for conference mobile apps to give information to guests.

# Group Pages
Pages related resources of the **Pages API**

## Pages Collection [/pages]
### List all Pages [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "General Info"
        }, {
          "id": 2, "title": "Schedule"
        }, {
          "id": 3, "title": "Speakers"
        }, {
          "id": 4, "title": "Sponsors"
        }, {
          "id": 5, "title": "Exhibit Map"
        }, {
          "id": 6, "title": "Transportation"
        }, {
          "id": 7, "title": "Eat•See•Shop•Sip"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
